### ISSUE TITLE
Merging files doesn't work

### ISSUE THREAD

**Issue by mzso** [inbasic/iaextractor#123]
Hi!
The downloaded streams are apparently not merged anymore.
I get no error message. I didn't change ffmpeg path, it was `D:\Programok\videÃ³\CLI\ffmpeg.exe` which used to work. I tried changing manually in the options. It changed to: `d:\Programok\videó\CLI\ffmpeg.exe` But the files are still not merged.
Tried the conversion tools window: I get the message to install a different addon.
After I do that. I can't set the ffmpeg path in th options window provided by Media Converter and Muxer:
The browse button doesn't work, and if I paste the path to ffmpeg it does not get saved.

I'm guessing `extensions.feca4b87-3be4-43da-a1b1-137c24220968@jetpack.ffmpegPath` is the about:config entry for the ffmpeg path because it had the matching value of `D:\Programok\videÃ³\CLI\ffmpeg.exe`.
However after changing the path in the options of this addon it shows up empty. Even though the path `d:\Programok\videó\CLI\ffmpeg.exe` is shown in the options.

**Comment by mzso** [comment]
Update:
It turns out, the only way to make conversion work again is to set the value of `extensions.feca4b87-3be4-43da-a1b1-137c24220968@jetpack.ffmpegPath` to `"d:\Programok\videó\CLI\ffmpeg.exe"` manually in about:config.

**Comment by inbasic** [comment]
Thanks for reporting the solution. Let's keep this open for others with the same issue.

**Comment by mzso** [comment]
I was hoping the UI could be fixed for this though.

**Comment by inbasic** [comment]
So the browse button cannot be fixed as there is no control over the value it sets. However I have done some modifications to the manual field. Hope this fixes the problem.
https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.0b1.xpi?raw=true

You should be able to paste the path in the manual field now.

**Comment by mzso** [comment]
[**@inbasic**](https://github.com/inbasic) commented on [2016. ápr. 2. 12:17 CEST](https://github.com/inbasic/iaextractor/issues/123#issuecomment-204688391 "2016-04-02T10:17:50Z - Replied by Github Comment Enhancer"):
> So the browse button cannot be fixed as there is no control over the value it sets. However I have done some modifications to the manual field. Hope this fixes the problem.  
> 
> [https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.0b1.xpi?raw=true](https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.0b1.xpi?raw=true)
> 
> You should be able to paste the path in the manual field now.

I see.

I'm wondering though whether it would be much work to put the settings in an own options window like many other addons do? (More then dealing with this built in options feature's flaws?)
It's not just that stuff is broken with this one, but it's also rather hard to find things, since it's a long unstructured list.

**Comment by inbasic** [comment]
In the latest build, I moved all the settings to an independent options window.
https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.0b3.xpi?raw=true

Please give it a through check as I had to change the code a lot to support options window.  https://github.com/inbasic/iaextractor/commit/2a21e43264a9a6a5bda4b5247900f197d567d19b
Note that I haven't yet checked the new window on Windows OS so please let me know if there is any UI issues.

**Comment by mzso** [comment]
Cool.
I accidentally clicked the ffmpeg download/configure thing, which then failed to download ffmpeg.
Now the browse button functions normally, so that's cool. Otherwise everything looks normal:
![iae-sw](https://cloud.githubusercontent.com/assets/4479090/14234527/3d3c679e-f9e5-11e5-9a7c-21c34ef67e22.PNG)

One more thing: I think it would be better for the settings window to be non-modal with an apply button. So that one could test the effects of settings without closing it and needing to re-open it again. And needing to find the proper option again, since it always starts with the first section.

**Comment by inbasic** [comment]
> I accidentally clicked the ffmpeg download/configure thing, which then failed to download ffmpeg

So sourceforge.net now displays a warning about storing cookies. You need to first accept it and then press the "Proceed" button;

![screen shot 2016-04-04 at 12 56 48](https://cloud.githubusercontent.com/assets/351062/14242124/d4949d3a-fa64-11e5-815e-85bc28371400.png)
 
> One more thing: I think it would be better for the settings window to be non-modal with an apply button. So that one could test the effects of settings without closing it and needing to re-open it again.

There is no control over how the options page is opened from about:addons page. However, if you open the options window from the toolbar button, it is not non-modal (version 0.5.0b5).
https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.0b5.xpi?raw=true

**Comment by mzso** [comment]
[**@inbasic**](https://github.com/inbasic) commented on [2016. ápr. 4. 10:51 CEST](https://github.com/inbasic/iaextractor/issues/123#issuecomment-205199382 "2016-04-04T08:51:32Z - Replied by Github Comment Enhancer"):
> > I accidentally clicked the ffmpeg download/configure thing, which then failed to download ffmpeg
> 
> So sourceforge.net now displays a warning about storing cookies. You need to first accept it and then press the "Proceed" button;
> 
> [![screen shot 2016-04-04 at 12 56 48](https://cloud.githubusercontent.com/assets/351062/14242124/d4949d3a-fa64-11e5-815e-85bc28371400.png)](https://cloud.githubusercontent.com/assets/351062/14242124/d4949d3a-fa64-11e5-815e-85bc28371400.png)
> 
It doesn't work. I can click the link, which opens in the backgound. No cookie warning comes up, but even if it did I couldn't click it without closing the options window. When I click download again it fails just the same. Maybe sourceforge is not the best place to download it from. Wouldn't github be better?

> 
> There is no control over how the options page is opened from about:addons page. However, if you open the options window from the toolbar button, it is non-modal (version 0.5.0b5).  
> 
I see. Too bad, another firefox nonsense. Anyway it still lacks the apply button when it's opened from the button, so there's no way to make use of the non-modal windows.

**Comment by inbasic** [comment]
> Anyway it still lacks the apply button when it's opened

There is no need for the apply button. Settings are saved as soon as they are changed.

**Comment by mzso** [comment]
[**@inbasic**](https://github.com/inbasic) commented on [2016. ápr. 5. 14:58 CEST](https://github.com/inbasic/iaextractor/issues/123#issuecomment-205790806 "2016-04-05T12:58:57Z - Replied by Github Comment Enhancer"):
> > Anyway it still lacks the apply button when it's opened
> 
> There is no need for the apply button. Settings are saved as soon as they are changed.

I don't think you're right. (It worked that way with the old settings)
Tested with changing the formats int the "Items in the injected panel" section. When I just change the settings nothing happens. After I press OK the shown formats change.

(BTW If that were the case than having an OK button would pointless)

**Comment by inbasic** [comment]
i just tried the latest release on a Windows machine. I still got the "OK" button even when the options window was opened from the toolbar panel. And yes you are right, preferences are stored once the OK button is pressed. Mac doesn't have the OK button and hence options are stored once they are changed.

Anyhow, I pushed a new dev version. Let me know if you can see the OK button now; https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.1b2.xpi?raw=true

**Comment by mzso** [comment]
[**@inbasic**](https://github.com/inbasic) commented on [2016. ápr. 11. 13:14 CEST](https://github.com/inbasic/iaextractor/issues/123#issuecomment-208291487 "2016-04-11T11:14:30Z - Replied by Github Comment Enhancer"):
> i just tried the latest release on a Windows machine. I still got the "OK" button even when the options window was opened from the toolbar panel. And yes you are right, preferences are stored once the OK button is pressed. Mac doesn't have the OK button and hence options are stored once they are changed.
> 
> Anyhow, I pushed a new dev version. Let me know if you can see the OK button now; [https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.1b2.xpi?raw=true](https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.1b2.xpi?raw=true)

I still have the okay button with that beta.

**Comment by inbasic** [comment]
Pressing the OK button saves the preferences, right?

**Comment by mzso** [comment]
Yes.
​

**Comment by inbasic** [comment]
so what is the problem with opening the options window from the toolbar button? You still have the OK button and the window is not modal.

**Comment by mzso** [comment]
The same as before...
You have no use of the modality if you can't apply the settings without closing the window. And pressing OK closes the options window.

**Comment by inbasic** [comment]
I see. I am not sure how to fix this. This is how Firefox handles preferences in Windows OS. It is possible to design a new options window and handle all the savings manually though it is going to be more complex.

**Comment by mzso** [comment]
Isn't there just an easy way to add an apply button?

**Comment by inbasic** [comment]
How about enabling this preference; `browser.preferences.instantApply`

**Comment by mzso** [comment]
[**@inbasic**](https://github.com/inbasic) commented on [2016. ápr. 12. 07:05 CEST](https://github.com/inbasic/iaextractor/issues/123#issuecomment-208707223 "2016-04-12T05:05:21Z - Replied by Github Comment Enhancer"):
> How about enabling this preference; `browser.preferences.instantApply`

That works. However it doesn't help people who don't know about it.

**Comment by mzso** [comment]
I noticed that the temp folder was spammed with files due to this addon and ran out of empty space.

I don't understand why this addon puts files there pointlessly, wasting space, and failing to clean up after.
Ffmpeg can read the source files directly and write to the output file directly. Yet I see both the dash streams and merged files there.

**Comment by inbasic** [comment]
@mzso please try https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.1b3.xpi?raw=true and let me know if the extension still fails to delete the tmp folder/file

> I don't understand why this addon puts files there pointlessly

FFmpeg is not good at handling non Unicode chars. That's the only reason.

**Comment by mzso** [comment]
Whoops. I meant the previous comment comment for #132. I'll respond there.
